version: '3.1'

services:
  #  mysql:
  #    image: mysql:5.6.49
  #    restart: always
  #    environment:
  #      MYSQL_DATABASE: db
  #      MYSQL_ROOT_PASSWORD: password
  #    ports:
  #      - '3306:3306'
  #    volumes:
  #      - my-db:/var/lib/mysql
  elasticsearch:
    image: elasticsearch:6.8.5
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node

#volumes:
#  my-db: