server:
  port: 8090

spring:
  application:
    name: trandyol-app
  datasource:
    url: jdbc:mysql://localhost:3306/db?useSSL=false
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect